version: '3'
services:
  bnelabwhfast:
    image: "pandaxs/whfast:latest"
    container_name: bnelab_whfast
    env_file:
      - .env.bnelab
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    volumes:
      - snaps-lab:/Receiver/snaps
    networks:
      - network1

  bnelab-hkdk-wx:
    image: "hookdeck/hookdeck-cli"
    container_name: bnelab_hkdk-wx
    environment:
      - TZ=Australia/Brisbane
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       /bin/hookdeck version
       [ -f $HOME/.config/hookdeck/config-lab.toml ] && echo "Hookdeck config found!" || /bin/hookdeck login
       /bin/hookdeck listen http://bnelab_whfast:10987 bnelab-webhooks
    volumes:
      - $HOME/.config/hookdeck/bnelab:/root/.config/hookdeck  # persist hookdeck config from local config directory
    networks:
      - network1

networks:
  network1:
    name: bnelab-whkdk
    
volumes:
  snaps-lab:
