version: '3'
services:
  wh_rcvr:
    image: "pandaxs/wh_rcvr:latest"
    container_name: webhook_receiver
    env_file:
      - .env
    ports:
      - 8216:8216
    volumes:
      - snaps-data:/Receiver/snaps
    networks:
      - network1

  hookdeck-alerttowx:
    image: "hookdeck/hookdeck-cli"
    container_name: hookdeck-alerttowx
    environment:
      - TZ=Australia/Brisbane
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       /bin/hookdeck version
       [ -f $HOME/.config/hookdeck/config.toml ] && echo "Hookdeck config found!" || /bin/hookdeck login
       /bin/hookdeck listen http://webhook_receiver:8116 alerttowx
    volumes:
      - $HOME/.config/hookdeck:/root/.config/hookdeck  # persist hookdeck config from local config directory
    networks:
      - network1

networks:
  network1:
    name: webhookdeck
    external: true

    
volumes:
  snaps-data:
