services:
  whfast:
    image: "pandaxs/whfast:v0.9"
    container_name: whfast
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    volumes:
      - snaps-data:/Receiver/snaps
    networks:
      - network1

  hkdk-wx:
    image: "hookdeck/hookdeck-cli"
    container_name: hkdk-wx
    restart: unless-stopped
    environment:
      - TZ=Australia/Brisbane
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       /bin/hookdeck version
       [ -f $HOME/.config/hookdeck/config.toml ] && echo "Hookdeck config found!" || /bin/hookdeck login
       /bin/hookdeck listen http://whfast:8220 alerttowx
    volumes:
      - $HOME/.config/hookdeck/whfast:/root/.config/hookdeck  # persist hookdeck config from local config directory
    networks:
      - network1

networks:
  network1:
    name: webhookdeck

    
volumes:
  snaps-data: